version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # https://hub.docker.com/r/timothyjmiller/prisma-studio
  prisma-studio:
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    ports: 
      - '5551:5555' 
    env_file: 
      - ./.env
    depends_on: 
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: 
      - ./.env
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - '8081:3000'

volumes:
  postgres:
